platform :ios, '9.0'
use_frameworks!
def pods
#pod 'GaugeKit'
#pod 'SwifterSwift'
pod 'BaiduMapKit'
pod 'Alamofire'
pod 'PySwiftyRegex'
#pod 'Hue'
#pod 'Just'
pod 'SwiftyJSON'
#pod 'Kingfisher'
#pod 'SwiftyBeaver'
#pod 'Eureka'
pod 'SnapKit'
pod 'TBEmptyDataSet'
#pod 'ESPullToRefresh'
#pod 'Former'
#pod 'AMScrollingNavbar'
#pod 'KRProgressHUD'
#pod 'KeychainSwift'
pod 'IQKeyboardManagerSwift'
#pod 'XLPagerTabStrip'
#pod 'R.swift'
#pod 'CryptoSwift'
#pod 'Presentr'
#pod 'Timepiece'
#pod 'IncrementableLabel'
pod 'AvoidCrash'
#pod 'LGButton'
#pod 'Charts'
#pod 'ASValueTrackingSlider'
#pod 'SwiftMessages'
#pod 'IBAnimatable'
#pod 'PeekPop'
#pod 'SwiftyMarkdown'
#pod 'Ji'
#pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift.git', :branch => 'feature/swift-3'
#pod 'animated-tab-bar', :git => 'https://github.com/Ramotion/animated-tab-bar.git', :branch => 'master'
#pod 'DrawerController', :git => 'https://github.com/sascha/DrawerController.git', :branch => 'swift-3.0'
#pod 'Blurable', :git => 'https://github.com/FlexMonkey/Blurable.git', :branch => 'master'
#pod 'ObjectMapper'
#pod 'OMAMovingAnnotations'
#pod 'PySwiftyRegex'
#pod 'SwiftForms'
#pod 'Dodo'
#pod 'IGListKit'
#pod 'GaugeKit'
#pod 'EFQRCode'
#pod 'SwiftDate'
#pod 'SwipyCell'
pod 'YILTableViewManager'
pod 'Moya'
#pod 'RxSwift'
#pod 'RxCocoa'
pod 'IGListKit'
#pod 'SwiftyUserDefaults'
#pod 'YNDropDownMenu'
pod 'WechatOpenSDK'
pod 'FHHFPSIndicator'
end

target 'DaLi' do
  pods
end
